[build]
  command = "npm run build"
  publish = ".next"

[functions]
  directory = "functions"

[[edge_functions]]
  path = "/hello"
  function = "hello"

[[edge_functions]]
  path = "/auth"
  function = "auth"

[[plugins]]
  package = "@netlify/plugin-nextjs"
